### ISSUE TITLE
createContext 的第二个参数优化更新的用法要被移除了

### ISSUE THREAD

**Issue by mysteryven** [MinJieLiu/heo#4]
https://github.com/MinJieLiu/heo/blob/24893f73b201983e170d94be2d90ff9e22264fcd/src/index.tsx#L22

React 有一个  [PR](https://github.com/facebook/react/pull/20953) ，现在已经把这种用法移除掉了。

可能我想得不够全面，但是感觉[这里](https://github.com/MinJieLiu/heo/blob/24893f73b201983e170d94be2d90ff9e22264fcd/src/index.tsx#L27)采用下面的写法就足够了：

```js
 const value = useMemo(() => {
    return useHook(initialState);
  }, [useHook])
```

**Comment by MinJieLiu** [comment]
这里目前只是为了少点代码，其实想实现这种效果很简单，用 ref 转发一下就够了，我后面改一下

**Comment by MinJieLiu** [comment]
你下面那种写法不行的，会破坏 hooks 的限制

**Comment by mysteryven** [comment]
> 你下面那种写法不行的，会破坏 hooks 的限制

破坏限制具体指的什么呢？可否赐教一下。

我目前的理解是，只要后面 value 一直不变，就都不会触发 context 的穿透更新。而使用 `useMemo` 包了一层就保证了这件事。毕竟 `useHook` 这个参数在调用 `createStore` 之后就不会改变了

**Comment by MinJieLiu** [comment]
https://zh-hans.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

**Comment by MinJieLiu** [comment]
useHook 本质是一个自定义 hook

**Comment by MinJieLiu** [comment]
@mysteryven https://github.com/MinJieLiu/heo/commit/6d4ae852203374989d080f9b0e8f71b702c80b14

**Comment by mysteryven** [comment]
> @mysteryven [6d4ae85](https://github.com/MinJieLiu/heo/commit/6d4ae852203374989d080f9b0e8f71b702c80b14)

看完了，很 nice
